version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: credit-card-postgres
    environment:
      POSTGRES_DB: credit_card_db
      POSTGRES_USER: credit_user
      POSTGRES_PASSWORD: credit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - credit-card-network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: credit-card-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - credit-card-network
    restart: unless-stopped

  # FastAPI后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: credit-card-backend
    environment:
      - DATABASE_URL=postgresql://credit_user:credit_password@postgres:5432/credit_card_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - credit-card-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端Web应用
  frontend:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: credit-card-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - credit-card-network
    restart: unless-stopped

  # Adminer数据库管理工具 (可选)
  adminer:
    image: adminer:latest
    container_name: credit-card-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - credit-card-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  credit-card-network:
    driver: bridge 