"""优化年费规则模型_移除rule_name_添加积分兑换_年费周期

Revision ID: dae3b2b54a2b
Revises: 
Create Date: 2025-06-08 17:33:39.554201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae3b2b54a2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库架构"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_fee_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.UUID(), nullable=True, comment='年费规则ID，关联annual_fee_rules表'))
        batch_op.create_foreign_key(None, 'annual_fee_rules', ['rule_id'], ['id'])

    with op.batch_alter_table('annual_fee_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_per_yuan', sa.Numeric(precision=6, scale=4), nullable=True, comment='积分兑换比例：1元对应的积分数，如1元=0.1积分则填0.1'))
        batch_op.add_column(sa.Column('annual_fee_month', sa.Integer(), nullable=True, comment='年费扣除月份，1-12'))
        batch_op.add_column(sa.Column('annual_fee_day', sa.Integer(), nullable=True, comment='年费扣除日期，1-31'))
        batch_op.drop_index('idx_annual_fee_rules_rule_name')
        batch_op.create_index('idx_annual_fee_rules_annual_month_day', ['annual_fee_month', 'annual_fee_day'], unique=False)
        batch_op.drop_column('waiver_period_months')
        batch_op.drop_column('rule_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库架构"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_fee_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='规则名称，如：刷卡次数减免-标准'))
        batch_op.add_column(sa.Column('waiver_period_months', sa.INTEGER(), autoincrement=False, nullable=True, comment='考核周期（月），通常为12个月'))
        batch_op.drop_index('idx_annual_fee_rules_annual_month_day')
        batch_op.create_index('idx_annual_fee_rules_rule_name', ['rule_name'], unique=False)
        batch_op.drop_column('annual_fee_day')
        batch_op.drop_column('annual_fee_month')
        batch_op.drop_column('points_per_yuan')

    with op.batch_alter_table('annual_fee_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rule_id')

    # ### end Alembic commands ### 