"""优化card模型_移除annual_fee字段_更新CardType为卡组织类型

Revision ID: 847bc5119087
Revises: dae3b2b54a2b
Create Date: 2025-06-08 17:52:55.062446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847bc5119087'
down_revision = 'dae3b2b54a2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库架构"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.alter_column('card_type',
               existing_type=sa.VARCHAR(length=20),
               comment='卡组织类型：visa/mastercard/unionpay/amex/jcb/discover/diners',
               existing_comment='卡片类型：credit/debit/business/student',
               existing_nullable=False)
        batch_op.drop_column('annual_fee')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库架构"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_fee', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False, comment='年费金额'))
        batch_op.alter_column('card_type',
               existing_type=sa.VARCHAR(length=20),
               comment='卡片类型：credit/debit/business/student',
               existing_comment='卡组织类型：visa/mastercard/unionpay/amex/jcb/discover/diners',
               existing_nullable=False)

    # ### end Alembic commands ### 