"""Create banks and credit_cards tables

Revision ID: da019d5eac6e
Revises: 66a0d1ee04e6
Create Date: 2025-06-13 10:27:35.834862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da019d5eac6e'
down_revision: Union[str, None] = '66a0d1ee04e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
